#!/usr/bin/env bash
# example-hook.sh
# ---
# Sample Claude Code hook generated by /meta-harness:build for {{project_name}}.
# Generated at: {{generated_at}}.
#
# Event: SessionStart
# ---
# When this hook would fire:
#   - Claude Code emits a `SessionStart` event when a new session is opened
#     against this project root. This script is the body that would run.
#
# Default status: DISABLED.
#   - hooks/hooks.json registers this hook with `"enabled": false` per ADR-0003
#     (slash + opt-in hooks; see the meta-harness plugin). To enable, flip the
#     entry's `enabled` to true AFTER you have read this file and understand
#     what it will run.
#
# Safety reminder:
#   - Hooks run inside your harness with the permissions configured in
#     .claude/settings.json. Treat every hook as code-on-event; review the
#     body before enabling.
#
# This stub is a no-op. It documents the contract and exits cleanly.

set -euo pipefail

echo "[hook:example-hook] SessionStart fired for {{project_name}}. (No-op stub.)"

# replace this with your hook logic

exit 0
