{
  "_generated_by": "meta-harness v1.0.0 (/meta-harness:build)",
  "_generated_at": "{{generated_at}}",
  "_project_name": "{{project_name}}",
  "_format_note": "This file uses a simple {\"hooks\": [...]} registry shape. If your Claude Code runtime expects a different schema, adapt this file accordingly. Each entry must have an `enabled` boolean; per ADR-0003 of meta-harness, defaults ship OFF.",
  "hooks": [
    {
      "name": "example-hook",
      "event": "SessionStart",
      "script": "hooks/example-hook.sh",
      "enabled": false,
      "description": "Sample hook generated by /meta-harness:build for {{project_name}}. Disabled by default per ADR-0003."
    }
  ]
}
