---
name: example-command
description: "Placeholder slash command stub generated by /meta-harness:build for {{project_name}}. Replace this with a real, project-specific command that dispatches to a named skill (see KB-3 criterion CAP-2)."
argument-hint: "[--flag <value>]"
allowed-tools:
  - Read
  - Edit
  - Bash
model: inherit
generated_by: "meta-harness v1.0.0 (/meta-harness:build)"
generated_at: "{{generated_at}}"
---

# `/example-command` — placeholder

> This file was generated as a STUB by `/meta-harness:build` for project
> **{{project_name}}**. Rename it to a verb describing what the command does,
> point it at a real skill in `skills/`, edit this file, and delete this note.
>
> The shape the 4-bucket rubric (KB-3 CAP-2) rewards is: a clear one-sentence
> purpose, an explicit dispatch to a named skill or agent, documented
> arguments, and a cross-link back to the skill.

## When to use this

Run this command when you want to: `<TODO: one sentence describing the user
intent this command serves>`.

## Arguments

| Argument | Default | Meaning |
|----------|---------|---------|
| `--flag <value>` | (none) | `<TODO: describe>` |

## Procedure (delegated)

This command's only job is to:

1. Validate arguments.
2. Print the cwd so the user can see which project root will be touched.
3. Hand off to the workflow skill at `skills/example-skill/SKILL.md`.

The skill is responsible for the actual work, the verification step, and the
output rendering. See that file for the procedure.

## Failure modes

| Code | Meaning |
|------|---------|
| `EXAMPLE_BAD_ARGS` | Invalid or missing argument. |
| `EXAMPLE_SKILL_FAILED` | The dispatched skill returned a non-zero status. |

## Examples

```
# Run with defaults.
/example-command

# Run with a flag.
/example-command --flag value
```

## Related

- `skills/example-skill/SKILL.md` — the procedural workflow this command
  dispatches to.
