---
skill_id: example-skill
name: Example Skill (placeholder)
description: "Placeholder skill stub generated by /meta-harness:build for {{project_name}}. Replace this with a real, project-specific skill. The shape below is what the 4-bucket rubric (CAP-1, CAP-2, CAP-5) rewards."
invoked_by:
  - commands/example-command.md
invokes:
  - "<TODO: name the agent(s) this skill orchestrates, e.g., agents/karpathy-evaluator>"
generated_by: "meta-harness v0.1.0 (/meta-harness:build)"
generated_at: "{{generated_at}}"
---

# Example Skill — placeholder

> This file was generated as a STUB by `/meta-harness:build` for project
> **{{project_name}}**. Rename the directory (`skills/example-skill/`) to a
> verb-shaped name describing what the skill actually does, edit this file,
> and delete this note.
>
> A skill is "long-form procedural knowledge for one workflow". For the
> shape the evaluator rewards, see KB-3 criteria CAP-1 (workflow exists),
> CAP-2 (commands dispatch to skills), and CAP-5 (composition with agents)
> in the bundled `meta-harness` plugin's `docs/theory/harness-4-bucket-principles.md`.

## Trigger

When to use this skill (replace with your actual trigger):

- User invokes `/<your-command>` in this project, or
- Skill is dispatched by another skill, or
- Hook event (named) fires and routes here.

## Inputs

| Input | Source | Required |
|-------|--------|----------|
| `<input-name>` | `<where it comes from>` | Yes / No |

## Outputs

- `<artifact-1>` written to `<path>` atomically (write `.tmp.$$`, then `mv`).
- A short human summary (4-8 lines) printed to stdout.

## Procedure

1. **Pre-flight.** Validate inputs. If a required input is missing, print the
   error code on stderr and exit non-zero. Do NOT continue with a partial
   set of inputs.
2. **Plan.** For non-trivial work (>1 file touched), emit a numbered plan via
   TodoWrite and wait for user confirmation. This satisfies CAP-3
   (plan-then-act discipline).
3. **Execute.** Perform the workflow's actual steps. Each step should:
   - Be idempotent where possible.
   - Log a one-line summary of what it did (which file, what change).
   - Stop on first error.
4. **Verify.** Run an explicit check (e.g., `<verification command>`) that
   confirms the outputs were produced correctly. Fail loudly if the check
   does not pass.
5. **Render.** Print the human summary and emit the structured output (JSON
   or otherwise) to stdout.

## DONE when

- All outputs from the "Outputs" section above are present, AND
- The verification step in (4) passed, AND
- The user has been shown the human summary.

If any of those is false, this skill is NOT done; surface the missing piece
and stop. Do not silently call this skill "complete".

## Failure modes

| Code | Meaning |
|------|---------|
| `EXAMPLE_INPUT_MISSING` | A required input was not supplied. |
| `EXAMPLE_VERIFY_FAILED` | Step 4 verification did not pass. |
| `EXAMPLE_WRITE_FAILED` | An atomic write step could not complete. |

## When to use this skill vs. another

Disambiguate from neighboring skills:

- Use this skill when `<your trigger condition>`.
- Use `<other-skill>` instead when `<their trigger condition>`.

CAP-5 specifically rewards harnesses whose skills cross-reference each other
and the agents they invoke. Filling this section is the cheapest way to lift
your Capabilities score.
