# {{project_name}}

> Claude Code harness for **{{project_name}}**, bootstrapped from `meta-harness`.
> Edit this file freely; the harness lives next to your product, not above it.

## Harness provenance

- Generated by: `meta-harness` v1.0.0 (`/meta-harness:build`)
- KB set version: `{{kb_set_version}}`
- KB manifest hash: `{{kb_manifest_hash}}`
- Generated at: `{{generated_at}}`

The harness above is the 4-bucket layout that the `karpathy-evaluator` agent
scores (Persona, Capabilities, Runtime, Meta-Governance). The KB set version
and manifest hash pin which rubric snapshot produced the bootstrap; recording
them here is what makes the score reproducible (per `docs/ADR-0001-static-kb-choice.md`).

This README satisfies KB-3 criteria **MG-1** (the harness has a README that
documents it) and **MG-4** (KB version + manifest hash are surfaced where an
operator can find them without grepping JSON).

## Quick start

- Read **`CLAUDE.md`** first — it is your project's Claude Code "constitution"
  and the place to record stack, conventions, and refusal boundaries.
- Look at **`skills/`** and **`commands/`** for the workflow surface. Each
  skill has a `SKILL.md` with numbered steps; each command names the skill
  it dispatches to.
- Run **`/meta-harness:evaluate`** at the project root to score this harness
  on the 4-bucket rubric. Re-run it after every meaningful harness edit to
  see how the score moves.

## Re-syncing the bundled KB

The `agents/karpathy-evaluator.md` file and the KB it references were vendored
into this project at build time. The upstream `meta-harness` plugin owns the
authoritative version. The intended re-sync command is `/meta-harness:manage`
(slated for the plugin's M4 milestone). Until then, re-running
`/meta-harness:build` against this directory refreshes the templated files;
existing local edits are surfaced as conflicts and never overwritten without
explicit approval (see `skills/harness-build/SKILL.md` Step 3).

## License and credits

See `LICENSE` for license terms. This harness was bootstrapped by the
`meta-harness` plugin — see https://github.com/seokan-jeong/meta-harness for the
upstream project, the KB sources, and the rubric.
